//! Country flags embedded at compile time, keyed by 3-letter team code.
//! PNGs are used in-app (egui image loader); SVGs in the printed HTML export.
//! Source: https://github.com/lipis/flag-icons (MIT).

/// Rasterized PNG bytes for a team code (for in-app rendering).
pub(crate) fn flag_png(code: &str) -> Option<&'static [u8]> {
    let bytes: &'static [u8] = match code {
        "ALG" => include_bytes!("../assets/flags/ALG.png"),
        "ARG" => include_bytes!("../assets/flags/ARG.png"),
        "AUS" => include_bytes!("../assets/flags/AUS.png"),
        "AUT" => include_bytes!("../assets/flags/AUT.png"),
        "BEL" => include_bytes!("../assets/flags/BEL.png"),
        "BIH" => include_bytes!("../assets/flags/BIH.png"),
        "BRA" => include_bytes!("../assets/flags/BRA.png"),
        "CAN" => include_bytes!("../assets/flags/CAN.png"),
        "CIV" => include_bytes!("../assets/flags/CIV.png"),
        "COD" => include_bytes!("../assets/flags/COD.png"),
        "COL" => include_bytes!("../assets/flags/COL.png"),
        "CPV" => include_bytes!("../assets/flags/CPV.png"),
        "CRO" => include_bytes!("../assets/flags/CRO.png"),
        "CUW" => include_bytes!("../assets/flags/CUW.png"),
        "CZE" => include_bytes!("../assets/flags/CZE.png"),
        "ECU" => include_bytes!("../assets/flags/ECU.png"),
        "EGY" => include_bytes!("../assets/flags/EGY.png"),
        "ENG" => include_bytes!("../assets/flags/ENG.png"),
        "ESP" => include_bytes!("../assets/flags/ESP.png"),
        "FRA" => include_bytes!("../assets/flags/FRA.png"),
        "GER" => include_bytes!("../assets/flags/GER.png"),
        "GHA" => include_bytes!("../assets/flags/GHA.png"),
        "HAI" => include_bytes!("../assets/flags/HAI.png"),
        "IRN" => include_bytes!("../assets/flags/IRN.png"),
        "IRQ" => include_bytes!("../assets/flags/IRQ.png"),
        "JOR" => include_bytes!("../assets/flags/JOR.png"),
        "JPN" => include_bytes!("../assets/flags/JPN.png"),
        "KOR" => include_bytes!("../assets/flags/KOR.png"),
        "KSA" => include_bytes!("../assets/flags/KSA.png"),
        "MAR" => include_bytes!("../assets/flags/MAR.png"),
        "MEX" => include_bytes!("../assets/flags/MEX.png"),
        "NED" => include_bytes!("../assets/flags/NED.png"),
        "NOR" => include_bytes!("../assets/flags/NOR.png"),
        "NZL" => include_bytes!("../assets/flags/NZL.png"),
        "PAN" => include_bytes!("../assets/flags/PAN.png"),
        "PAR" => include_bytes!("../assets/flags/PAR.png"),
        "POR" => include_bytes!("../assets/flags/POR.png"),
        "QAT" => include_bytes!("../assets/flags/QAT.png"),
        "RSA" => include_bytes!("../assets/flags/RSA.png"),
        "SCO" => include_bytes!("../assets/flags/SCO.png"),
        "SEN" => include_bytes!("../assets/flags/SEN.png"),
        "SUI" => include_bytes!("../assets/flags/SUI.png"),
        "SWE" => include_bytes!("../assets/flags/SWE.png"),
        "TUN" => include_bytes!("../assets/flags/TUN.png"),
        "TUR" => include_bytes!("../assets/flags/TUR.png"),
        "URU" => include_bytes!("../assets/flags/URU.png"),
        "USA" => include_bytes!("../assets/flags/USA.png"),
        "UZB" => include_bytes!("../assets/flags/UZB.png"),
        _ => return None,
    };
    Some(bytes)
}

/// SVG bytes for a team code (for the printed HTML, rendered by the browser).
pub(crate) fn flag_svg(code: &str) -> Option<&'static [u8]> {
    let bytes: &'static [u8] = match code {
        "ALG" => include_bytes!("../assets/flags/ALG.svg"),
        "ARG" => include_bytes!("../assets/flags/ARG.svg"),
        "AUS" => include_bytes!("../assets/flags/AUS.svg"),
        "AUT" => include_bytes!("../assets/flags/AUT.svg"),
        "BEL" => include_bytes!("../assets/flags/BEL.svg"),
        "BIH" => include_bytes!("../assets/flags/BIH.svg"),
        "BRA" => include_bytes!("../assets/flags/BRA.svg"),
        "CAN" => include_bytes!("../assets/flags/CAN.svg"),
        "CIV" => include_bytes!("../assets/flags/CIV.svg"),
        "COD" => include_bytes!("../assets/flags/COD.svg"),
        "COL" => include_bytes!("../assets/flags/COL.svg"),
        "CPV" => include_bytes!("../assets/flags/CPV.svg"),
        "CRO" => include_bytes!("../assets/flags/CRO.svg"),
        "CUW" => include_bytes!("../assets/flags/CUW.svg"),
        "CZE" => include_bytes!("../assets/flags/CZE.svg"),
        "ECU" => include_bytes!("../assets/flags/ECU.svg"),
        "EGY" => include_bytes!("../assets/flags/EGY.svg"),
        "ENG" => include_bytes!("../assets/flags/ENG.svg"),
        "ESP" => include_bytes!("../assets/flags/ESP.svg"),
        "FRA" => include_bytes!("../assets/flags/FRA.svg"),
        "GER" => include_bytes!("../assets/flags/GER.svg"),
        "GHA" => include_bytes!("../assets/flags/GHA.svg"),
        "HAI" => include_bytes!("../assets/flags/HAI.svg"),
        "IRN" => include_bytes!("../assets/flags/IRN.svg"),
        "IRQ" => include_bytes!("../assets/flags/IRQ.svg"),
        "JOR" => include_bytes!("../assets/flags/JOR.svg"),
        "JPN" => include_bytes!("../assets/flags/JPN.svg"),
        "KOR" => include_bytes!("../assets/flags/KOR.svg"),
        "KSA" => include_bytes!("../assets/flags/KSA.svg"),
        "MAR" => include_bytes!("../assets/flags/MAR.svg"),
        "MEX" => include_bytes!("../assets/flags/MEX.svg"),
        "NED" => include_bytes!("../assets/flags/NED.svg"),
        "NOR" => include_bytes!("../assets/flags/NOR.svg"),
        "NZL" => include_bytes!("../assets/flags/NZL.svg"),
        "PAN" => include_bytes!("../assets/flags/PAN.svg"),
        "PAR" => include_bytes!("../assets/flags/PAR.svg"),
        "POR" => include_bytes!("../assets/flags/POR.svg"),
        "QAT" => include_bytes!("../assets/flags/QAT.svg"),
        "RSA" => include_bytes!("../assets/flags/RSA.svg"),
        "SCO" => include_bytes!("../assets/flags/SCO.svg"),
        "SEN" => include_bytes!("../assets/flags/SEN.svg"),
        "SUI" => include_bytes!("../assets/flags/SUI.svg"),
        "SWE" => include_bytes!("../assets/flags/SWE.svg"),
        "TUN" => include_bytes!("../assets/flags/TUN.svg"),
        "TUR" => include_bytes!("../assets/flags/TUR.svg"),
        "URU" => include_bytes!("../assets/flags/URU.svg"),
        "USA" => include_bytes!("../assets/flags/USA.svg"),
        "UZB" => include_bytes!("../assets/flags/UZB.svg"),
        _ => return None,
    };
    Some(bytes)
}
