//! Country flag SVGs embedded at compile time (from the flag-icons project),
//! keyed by 3-letter team code. Source: https://github.com/lipis/flag-icons (MIT).

/// The embedded SVG bytes for a team code, e.g. `MEX` -> Mexico's flag.
pub(crate) fn flag_svg(code: &str) -> Option<&'static [u8]> {
    let bytes: &'static [u8] = match code {
        "ALG" => include_bytes!("../assets/flags/ALG.svg"),
        "ARG" => include_bytes!("../assets/flags/ARG.svg"),
        "AUS" => include_bytes!("../assets/flags/AUS.svg"),
        "AUT" => include_bytes!("../assets/flags/AUT.svg"),
        "BEL" => include_bytes!("../assets/flags/BEL.svg"),
        "BIH" => include_bytes!("../assets/flags/BIH.svg"),
        "BRA" => include_bytes!("../assets/flags/BRA.svg"),
        "CAN" => include_bytes!("../assets/flags/CAN.svg"),
        "CIV" => include_bytes!("../assets/flags/CIV.svg"),
        "COD" => include_bytes!("../assets/flags/COD.svg"),
        "COL" => include_bytes!("../assets/flags/COL.svg"),
        "CPV" => include_bytes!("../assets/flags/CPV.svg"),
        "CRO" => include_bytes!("../assets/flags/CRO.svg"),
        "CUW" => include_bytes!("../assets/flags/CUW.svg"),
        "CZE" => include_bytes!("../assets/flags/CZE.svg"),
        "ECU" => include_bytes!("../assets/flags/ECU.svg"),
        "EGY" => include_bytes!("../assets/flags/EGY.svg"),
        "ENG" => include_bytes!("../assets/flags/ENG.svg"),
        "ESP" => include_bytes!("../assets/flags/ESP.svg"),
        "FRA" => include_bytes!("../assets/flags/FRA.svg"),
        "GER" => include_bytes!("../assets/flags/GER.svg"),
        "GHA" => include_bytes!("../assets/flags/GHA.svg"),
        "HAI" => include_bytes!("../assets/flags/HAI.svg"),
        "IRN" => include_bytes!("../assets/flags/IRN.svg"),
        "IRQ" => include_bytes!("../assets/flags/IRQ.svg"),
        "JOR" => include_bytes!("../assets/flags/JOR.svg"),
        "JPN" => include_bytes!("../assets/flags/JPN.svg"),
        "KOR" => include_bytes!("../assets/flags/KOR.svg"),
        "KSA" => include_bytes!("../assets/flags/KSA.svg"),
        "MAR" => include_bytes!("../assets/flags/MAR.svg"),
        "MEX" => include_bytes!("../assets/flags/MEX.svg"),
        "NED" => include_bytes!("../assets/flags/NED.svg"),
        "NOR" => include_bytes!("../assets/flags/NOR.svg"),
        "NZL" => include_bytes!("../assets/flags/NZL.svg"),
        "PAN" => include_bytes!("../assets/flags/PAN.svg"),
        "PAR" => include_bytes!("../assets/flags/PAR.svg"),
        "POR" => include_bytes!("../assets/flags/POR.svg"),
        "QAT" => include_bytes!("../assets/flags/QAT.svg"),
        "RSA" => include_bytes!("../assets/flags/RSA.svg"),
        "SCO" => include_bytes!("../assets/flags/SCO.svg"),
        "SEN" => include_bytes!("../assets/flags/SEN.svg"),
        "SUI" => include_bytes!("../assets/flags/SUI.svg"),
        "SWE" => include_bytes!("../assets/flags/SWE.svg"),
        "TUN" => include_bytes!("../assets/flags/TUN.svg"),
        "TUR" => include_bytes!("../assets/flags/TUR.svg"),
        "URU" => include_bytes!("../assets/flags/URU.svg"),
        "USA" => include_bytes!("../assets/flags/USA.svg"),
        "UZB" => include_bytes!("../assets/flags/UZB.svg"),
        _ => return None,
    };
    Some(bytes)
}
